### ISSUE TITLE
Creating an 'empty' database doesn't create a .db file (OSX 10.10.5 and SQLite version 3.8.5)

### ISSUE THREAD

**Issue by miclp** [learn-co-curriculum/sql-queries-basic-readme#14]
In the instructions for "Creating our Database", typing

`sqlite3 pets_database.db`
`.quit`
`ls`

the output of ls didn't include the new database.  Apparently if you run:
`sqlite3 pets_database.db ""`
or a 'filler' command like:
`sqlite3 pets_database.db .schema;`
it does create the file, however.  (No .db file is created until some sort of command is issued, even if that command is "")

**Comment by gj** [comment]
#22 should take care of this.
