### ISSUE TITLE
There is an extra "," in Group BY examples SELECT breed, owner_id, COUNT(breed) FROM cats GROUP BY breed, owner_id;

### ISSUE THREAD

**Issue by Daviicode** [learn-co-curriculum/sql-queries-basic-readme#27]

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
