### ISSUE TITLE
Wrong command, missed ","

### ISSUE THREAD

**Issue by aabuauf** [learn-co-curriculum/sql-queries-basic-readme#29]
When i tried to run "SELECT breed COUNT(breed) FROM cats GROUP BY breed;" it gave me error "Error: near "(": syntax error". I fixed it by adding ",". to be "SELECT breed, COUNT(breed) FROM cats GROUP BY breed;"

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
