### ISSUE TITLE
Missing coma on SQL code

### ISSUE THREAD

**Issue by audefaucheux** [learn-co-curriculum/sql-queries-basic-readme#31]
The below code doesn't work

SELECT breed COUNT(breed) FROM cats GROUP BY breed;

 I believe it is because a coma is missing between "breed" and "COUNT(breed)"

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
