### ISSUE TITLE
talk about fields

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/sql-queries-basic-readme#4]
in prep for bear organizer.

**Comment by joshuabamboo** [comment]
@SophieDeBenedetto can you elaborate on this. I don't understand the issue.

**Comment by SophieDeBenedetto** [comment]
So near organizer asks them to write queries like SELECT bears.name FROM Bears;

But we don't show them this tablename.columnname syntax. We should include that here.
